<?php
session_start();
include('../connection.inc.php');
include('../function.inc.php');
unset($_SESSION['PROSECUTOR_IS_LOGIN']);
unset($_SESSION['PROSECUTOR_USER']);
unset($_SESSION['PROSECUTOR_USER_NAME']);
unset($_SESSION['PROSECUTOR_ID']);
redirect('login.php');
?>
